---
title: "Ref. GEB-2020-0155 - Response to reviewers"
author: "Eduardo Fernández Pascual"
date: "19/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please, find below my revision of the manuscript. I have considered and applied all suggestions. Considering the major issues, I have (1) expanded the explanation of the chosen biome and the creation of the species list; (2) clarified the missing full texts issue, providing a more detailed description, a PRISMA flow chart, and BibTeX files with the missing references; and (3) expanded the database to include the controlling factors required by the reviewers, such as substrate and number of containers.

# Response to the Editor

> I recommend that the manuscript be rejected with an opportunity to resubmit. The reviewers and myself agreed that the premise of the study was very interesting and relevant to the journal's audience, and appreciate the extensive work that went into its creation. However, a number of issues were identified, which I think preclude publication in present form, and whose resolution would potentially require extensive work on the part of the authors.

> First, the database's content and scope seems broader than warranted by its contents. The first reviewer and I both agree that the data do not necessarily provide full coverage of the proposed biome, and may contain species from beyond it. Additionally, I note that all of the sPlot records used to create a species list are from the Northern hemisphere, when the temperatre / broadleaf forest biome occurs widely in the southern hemisphere. While some of the identified studies end up sourcing data from southern hemisphere sites, it seems inaccurate and overly ambitious to suggest the dataset cover this biome. I am not sure that database with only northern hemisphere coverage of one biome, and with strong biases towards the species and sites represented in sPlot, would be of sufficient interest to receive support in the journal. I encourage the authors to expand the scope of their study, or alternatively provide a robust justification for the current scope, and a clearer title / narrative concomitant with the data.

The editor is right that the biome is also found in the southern hemisphere, although the extension there is smaller than in the northern hemisphere. In the new version of the manuscript, there is a longer explanation of why the NH biome was chosen, and how the species were selected. Summarising, the temperate broadleaf and mixed forests of the Northern Hemisphere were chosen as the subject of a sPlot project. Only the NH was chosen because it forms a coherent biogeographical unit, since it shared a common history during the Tertiary. The SH forests, on the other hand, are separated (and smaller) units and were not connected to the northern forests. This database was created for that specific sPlot project, and it was decided to do so because we expected that the number of germination references would be the highest, since many classical research groups have worked within the NH temperate broadleaf and mixed forests biome. This is developed in more detail in the manuscript and in the response to the reviewers.

In addition, the title has been changed to *Sylvan Seeds, a database and web app to explore the seed germination ecology of temperate broadleaf and mixed forests of the northern hemisphere*.

In any case, and in my personal view, I believe this is the more complete database of raw germination data for a coherent ecological unit and, spanning three continents of a densely populated and significant biome, it has enough global interest for the journal.

> Reviewer #1 also notes that 1/3 of the considered studies were omitted due to access issues; I suggest the authors try to resolve this point, or robustly clarify the justification for this choice. As the manuscript stands currently this text is not very convincing for a reader.

Please see the response to the reviewers about this point.

> Second, the first reviewer identified several issues related to the methodology used for the meta-analysis and literature search. I am sympathetic to these points and suggest the authors revisit their search criteria and data, or provide a robust response to these criticisms.

Please see the response to the reviewers about this point.

> As such, I do not think the data paper is ready to be accepted in present form, but am very willing to consider a thoroughly revised version.

# Responde to Referee 1

> The manuscript describes a dataset of species germination rates where the species were selected based on the sPlot species lists for temperate biomes. The shiny app is a nice addition that could be of use to the broader public with proper dissemination. It is interesting data to compile that will surely be valuable, but the scope of the biomes investigated and a lack of important methodological detail from the germination experiments limits the utility of the data. These concerns and a few others are detailed below. 

> I wonder if defining the biome as “temperate broadleaf and mixed forests” is appropriate. There appears to be a number of species that generally occur in grasslands and biomes/habitats outside of forests (e.g. Dactylis glomerata, Achillea millifolium, Festuca ovina, etc.). Did each paper specify that the populations of seed collection were forested? If not, I recommend using something like a Whittaker biome diagram to describe the biomes as temperate rain, deciduous and dry forests, and grass/shrublands. Or just add additional biomes from the WWF classifications.

The new version of the manuscript contains a more detailed explanation of the reason to select the biome, and of the methodology used to construct the list of species. Please see the response to the editor and the manuscript for more comments on this.

The TBMF biome (in the northern hemisphere) is the area which was used to create the list of frequent species, for which the database was then compiled.  Biomes are defined as *relatively large units of land containing a distinct assemblage of natural communities and species, with boundaries that approximate the original extent of natural communities prior to major land-use change*. Thus, the TBMF biome does not contain only forests, but many other habitats such as heathlands, meadows, alpine grasslands, mires, dunes, etc. However, the plots used to create the list were filtered to be only forested plots (i.e., they were selected when they met the criterion that tree species dominated their plant cover). The list that has been produced includes species that occur with high frequency in forested plots of the TBMF biome in the nothern hemisphere. These are trees, shrubs, and herbaceous understory plants adapted to shade. But also species of forest margins, openings, riparian forests, ruderalized forests, etc.

The species mentioned by the reviewer are indeed species of the TBMF biome, and, even if today they may have their optimum in semi-natural meadows and pastures, they can occur also in forested plots (and in fact they do, as sown by the vegetation relevés we used). *Dactylis glomerata* and *Achillea millifolium* are species of mesic meadows (*Molinio-Arrhenatheretea*), which are secondary communities developped by human intervention over habitats that would be naturally occupied by temperate forests. The traditional interpretation of the origin of these communities is that they originated in forest margin communities that colonized the openings created by humans. Therefore, it is not surprising that these species are recorded with relative frequency in forest plots, as indeed they are. Similarly, it is not surprising that dry grassland (*Festuco-Brometea*) species such as *Festuca ovina* are also recorded in forest plots, especially in contact areas, as these are also communities that expanded over landscapes that would naturally be forests.

I agree that the seed lot coordinates that are provided with the database could be used to construct a Whittaker diagram of the seed lots, or alternatively to asign them to WWF biomes. But I feel that this is more of an analytical usage of the data, which can be done by any user with the information provided in the dataset. Still, I am willing to do such tasks if the editor finds them essential.

> The justification for restricting the search to certain biomes and species is weak (Lines 49-50), especially given sPlot is a global database. If picking these biomes covers most of the available data, why not extend beyond this biome given the added work is relatively minimal? Then the dataset would be truly global. There are a lot of papers on germination outside of this biome that could make for valuable comparisons (e.g., tundra/alpine biomes from Vandvik et al. 2017. Botany 95:73-88; Tropical forests from Yu et al. 2008. Plant Ecology 297:1-16). Why not expand the search to all species within sPlot? If the search is expanded to all species in sPlot, does the number of articles requiring processing become unreasonable? This would make for a better justification for restricting the search. 

I have included a more detailed description of the reasons behind chosing the TBMF biome to construct the database: *The building of the dataset was part of a research project conducted within the sPlot initiative (Bruelheide et al., 2019), specifically sPlot’s project #12 (https://www.idiv.de/en/sdiv/working_groups/wg_pool/splot/projects.html). The goal of sPlot #12 was to study taxonomical and functional plant diversity in deciduous forests, which are dominant in temperate latitudes with mild to cold winters and relatively warm and wet summers. In the northern hemisphere, they also form a coherent evolutionary and biogeographic unit, sharing a common Tertiary history until they became separated between North America, Asia and Europe (Milne & Abbott, 2002).*

Completing the database for all the species in sPlot is a worthwhile long-term goal (as mentioned in the *Utility of the database* section of the manuscript), and one that I am interested in contributing to in the future. But it was completely beyond the resources I had to construct this database, which depended on a 2-year personal grant. It took me 9 months of focused work to build a database for 1,393 species. There are 54,519 species in sPlot 2.1 (*Bruelheide, H., Dengler, J., Jiménez‐Alfaro, B., Purschke, O., Hennekens, S. M., Chytrý, M., ... & Aubin, I. (2019). sPlot–A new tool for global vegetation analyses. Journal of Vegetation Science, 30(2), 161-186*). Therefore, a rough estimate is that it would take me 29 years of work to do a database for all sPlot species! Even if the time would probably be shorter (because I do expect the number of references would be lower outside the TBMF biome), the number of references would be expanding each year with new research. So, because one has to start somewhere, I chose to do it in connection to sPlot project 12, which focused on temperate broadleaf and mixed forests of the northern hemisphere; and I chose to do it because this biome has received much attention in seed research. 

> The literature search would benefit from more description and/or investigation. What made a full text impossible to access? Not having access to a few full texts is understandable, but 236 would make up more than 1/3 of the 611 that were to be relevant. This data could be very important to the completeness of the dataset. Using PRISMA guidelines for proper meta-analysis data gather is highly recommended (http://www.prisma-statement.org).

Just to be precise, the proportion of not-found information is actually smaller. Of 1489 references for which I searched for the full text, I found 1253 (NOTE: While doing the revisions, I have found and corrected small discrepancies in the numbers of references, caused because a few of the records were removed by a mismatch during taxon name standardization). Of these, 639 (51%) were not relevant. If we assume the same proportion of relevant references in the cases for which I could not find the full text, we can estimate that there were 116 relevant articles which I could not include in the database: 16% of the potentially relevant references (614 found + 116 estimated not found = 730; 116/730 =  0.16). Furthermore, I must note that information is not homogenesouly distributed thorough the references: there are many references for some popular species, and fewer references for rarer species. Therefore the amount of valuable information does not increase linearly with increasing number of references, and it is very likely that a large proportion of that 16% is made up of references considering species which are already in the database. In conclusion, I believe that the amount of missing information is within reasonable limits. 

Be that as it may, I have improved the description of data gathering in the text, including a description of the process of finding full texts: *An effort was made to access the full text of all these references, using in order the following channels: (i) “Find Full Text” functionality in EndNote X9, (ii) online access to the journals using the institutional subscriptions of the University of Oviedo; (iiI) request to the authors through ResearchGate; (iv) general search of pdf files in Google using the article details. Unfortunately, 236 references could not be accessed. Most of these belonged to smaller publishers not included in the subscriptions of the University of Oviedo, and to older journal volumes which had not been digitalised.*

I have also included some supplementary materials to describe the data gathering: the boolean search string I used in the Web of Science, and a PRISMA flow chart. 

Additionally, I have added the lists of the three types of references (non-relevant, found and not-found) as BibTeX supplementary files. In this way, it will be possible to check what I did, and to complete it in the future by accessing the references that I could not find.

> There appears to be a lot of important information missing in the dataset that would allow a user of the dataset to control for methodological artifacts or biases. For example: what kind of substrate were the seeds germinated in (Agar? Soil? Sand?)? What was the density of seeds sown? How large were the containers holding the seeds? How many replicates were there to determine the number germinated versus germinable? Were any treatments, such as drought or nutrient addition, used in the experiment? Were the seeds sown in a monoculture?

As requested, I have revised the references to retrieve the requested information, and added it to the database: type of substrate; type and dimensions of the containers; number of containers and number of seeds sown per container; treatments of sterilization and nutrients. Density of seeds is not reported in the references, but it can be estimated from the dimension of the containers and the number of seeds sown. All cases included in the database correspond to monoculture experiments, and special treatments (drought, heavy meatals, smoke, etc.) were not included; this is now stated in the text. Please see the manuscript for the description of the new variables in the database. 

> Most of the studies would have replicated germination trials (e.g. sown 100 seeds across 5 replicates: 20 seeds per replicate). Therefore, there is likely true error estimates (and mean percent germination) that can be obtained from the papers. These are a highly desirable metrics from the papers and would improve the error estimates in the shiny app as well.

As requested, I have included the number of containers ("replicates") and number of seeds sown per replicate in the database.

> Line 12- add an “and” so that it reads “darkness, and constant or alternating”

Done.

> Line 16- Will the data collection be continuous? Maybe assign a final year here.

Done.

> Line 31- add an of; “all of these”

Done.

> Line 35- use commas instead of –

Done.

> Line 39-40- “which implies a set of derived complications in the analytical treatment of the data”- unclear what this means and how it applies to germination as a number of successes given seeds sown (trials).

I have removed the whole sentence.

> Line 45- Rather than “at this and that temperature”, try “across a temperature gradient”?

Done.

> Line 95- give a brief explanation of GA3

Done.

> Line 104-105- Remove highlight of Fig. 1.

Done.

> Line 108- incorrect degree symbol. 

It was the degree symbol rendered in the Calibri font, the new manuscript is in Arial.

> Line 154- remove the “a” to read “can have wide applicability”

Done.

> Line 155-157- Try “The data can extend current trends in global analyses of plant traits at species (Diaz et al., 2016) and community levels (Bruelheide t al., 2018) to seed germination.”

Done.

> Line 160- Remove “to”

Done.

> Line 262- As the authors note, the references will need cleaning.

Indeed.

> Can the species names be searchable in addition to the drop-down menu in the shiny app?

The species name can be deleted, and then one can write in the box. This will trigger an autocomplete, which will allow to search.

> There are special character errors in the “Reference” column of the dataset: e.g., «ali?kan, O., et al. (2012). "Influences of presowing treatments on the germination and emergence of fig seeds (Ficus carica L.)." Acta Scientiarum. Agronomy 34(3): 293-297.

This should be fixed now.

# Responde to Referee 2

> This data paper introduces a new resource available to ecologists: a data base and associated app summarising seed germination data for a large number of plant species in the temperate broadleaf/mixed forest biome. The authors used an extensive literature search to identify sources of germination data, and have gone through a substantial effort in extracting data from a large number of published articles. The resulting ‘Sylvan Seeds’ data base and app has the potential to be a valuable tool for researchers and applied foresters. I had a quick play around with the app – it provides nice species-specific data summaries (although I think the data base itself is going to be a more useful resource).

> I have little to criticise in terms of the approaches used (which seem sound), but believe that the presentation would benefit from a few changes to make it more reader friendly and accessible for people whose main interest might not be in seed ecology and to potential non-academic users of the database/app:

> L1 (Title): I am not sure how many people will immediately know what a ‘shiny app’ is. (I did not...) Could another more general term be used?

I changed it to *web app*.

> L5 (Motivation): This section could perhaps start with a sentence on why seed germination is an important phenomenon in ecology?

Done.

> L9-10: “Data has been gathered using a meta-analytical approach to search the literature.” Meta-analytical approach may suggest that some kind of data analysis was involved. Could be changed to something along the lines of “Data were gathered using a systematic literature search approach” or similar. (Later in the text you could then mention that the exact approach taken was inspired by approaches typically used in meta-analyses?) 

Changed as suggested.

> L14: “across the biome and beyond” – unclear meaning

Changed to *Seed lots collected throughout the biome and in neighbouring areas*.

> L16: today -> March 2019?

Changed to the year of the most recent seed lot, 2017.

> L17: frequent -> common?

I believe it is more appropiate to use frequent, as frequency is the common term in plant ecology: *Frequency is the number of times a plant species occurs in a given number of quadrats*. Frequency, thus defined, was the criterion used to include species in the search.

> L20: wide -> wider?

Changed.

> L25: Again, considering the broad readership of Global Ecology and Biogeography, it might be helpful to start with a sentence or two on the importance of studying seed traits/germination/seed ecology (and – given the journal – ideally also something on why a global approach can contribute to the field of seed ecology). 

Done.

> L41: scarcity of -> lack of? (Alternatively, if such data bases exist, but there are only few of them, stick to original wording but mention which ones exist.)

Changed to *lack of*.

> L45: at this and that temperature -> at various temperatures

Changed to *accross a temperature gradient* as suggested by referee 1.

> L49-50: home of many of the classical research groups in seed ecology -> research focus of (…) or similar?

Changed to *At the same time, a relatively high number of classic seed biology research groups have worked within the TBMFNH areas, e.g. in the USA (Baskin, 1995), the UK (Grime et al., 1981), Belgium (Van Assche & Vandelook, 2006) and Japan (Washitani, 1988). *.

> L51: see previous comment regarding reference to meta-analysis

Changed to *To gather data for the project, a systematic literature search (Koricheva et al., 2013) was applied to a list of frequent species representing the flora of the TBMFNH.*

> L57: not all readers might be familiar with the term vegetation relevé -> provide brief explanation?

The following explanation has been added: *(i.e. records of plant species co-occurring in a sampling plot)*

> L58: the reference to sPlot’s project #12 might not mean much to people not involved with sPlot. -> Provide link to website or further explanation?

I have included the following description: *The building of the dataset was part of a research project conducted within the sPlot initiative (Bruelheide et al., 2019), specifically sPlot’s project #12 (https://www.idiv.de/en/sdiv/working_groups/wg_pool/splot/projects.html). The goal of sPlot #12 was to study taxonomical and functional plant diversity in deciduous forests, which are dominant in temperate latitudes with mild to cold winters and relatively warm and wet summers. In the northern hemisphere, they also form a coherent evolutionary and biogeographic unit, sharing a common Tertiary history until they became separated between North America, Asia and Europe (Milne & Abbott, 2002).*. Unfortunately, no articles derived from sPlot #12 have been finished so far, so I cannot cite them, which would be the ideal solution.

> L72: ‘To obtain a final list of species (…)’. The primary reason for focusing on the subset of species that were present in a minimum of 5% of the relevés of an ecoregion was presumably to make the work achievable given the large number of species (>7000) in the full species pool?

There was the practical reason mentioned by the reviewer, but also a methodological consideration. I have added the following explanation: *There were two reasons to use this frequency threshold: (i) it made the search achievable with the resources available; and (ii) it filtered out rare species that may not be representative of TBMFNH, and which could have been recorded for a variety of reasons (wrong taxonomical identifications, mistakes in plot coordinates, border areas, unnatural areas such as parks, etc.).*  

> L81-82: “(…) for 236 it was impossible to access the full text.” Unclear meaning: Was this because of lack of institutional licenses for accessing journals, or because of something else?

Please see the response to referee 1 about the same question. The causes are now described as follows: *An effort was made to access the full text of all these references, using in order the following channels: (i) “Find Full Text” functionality in EndNote X9, (ii) online access to the journals using the institutional subscriptions of the University of Oviedo; (iiI) request to the authors through ResearchGate; (iv) general search of pdf files in Google using the article details. Unfortunately, 236 references could not be accessed. Most of these belonged to smaller publishers not included in the subscriptions of the University of Oviedo, and to older journal volumes which had not been digitalised.*.

> L95: GA3 -> gibberellic acid (to help readers who are less familiar with the topic, could perhaps also mention that GA3 speeds up seed germination)

Done.

> L96: the term ‘response variable’ suggests that you conducted some kind of statistical analysis. -> Delete term or change wording.

Removed *the response variable* part of the sentence.